# Generated by Django 5.2.5 on 2025-08-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_auto_20250818_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('frame', models.ImageField(blank=True, help_text='Snapshot of the frame where violation was detected', null=True, upload_to='alerts/')),
                ('alert_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='HIGH', help_text='Severity level of the alert', max_length=10)),
                ('is_alert', models.BooleanField(default=True, help_text='Mark whether this detection triggered an alert')),
            ],
            options={
                'verbose_name': 'Safety Alert',
                'verbose_name_plural': 'Safety Alerts',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='UserInput',
        ),
    ]
