# Generated by Django 5.2.5 on 2025-08-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0003_safetyalert_delete_userinput'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='safetyalert',
            options={},
        ),
        migrations.RemoveField(
            model_name='safetyalert',
            name='alert_level',
        ),
        migrations.RemoveField(
            model_name='safetyalert',
            name='frame',
        ),
        migrations.RemoveField(
            model_name='safetyalert',
            name='is_alert',
        ),
        migrations.RemoveField(
            model_name='safetyalert',
            name='label',
        ),
        migrations.AddField(
            model_name='safetyalert',
            name='alert_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='safetyalert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='alerts/'),
        ),
        migrations.AddField(
            model_name='safetyalert',
            name='worker_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='safetyalert',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
