# Generated by Django 5.2.5 on 2025-08-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0004_alter_safetyalert_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('violation_type', models.CharField(choices=[('NO_HELMET', 'No Helmet Detected'), ('NO_VEST', 'No Safety Vest Detected')], max_length=50)),
                ('camera_id', models.CharField(blank=True, max_length=100, null=True)),
                ('snapshot', models.ImageField(upload_to='snapshots/')),
            ],
        ),
        migrations.DeleteModel(
            name='SafetyAlert',
        ),
    ]
