# Generated by Django 5.2.5 on 2025-08-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0005_alert_delete_safetyalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='clip_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='detected_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='image_caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='people_detected',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='snapshots/'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='violation_type',
            field=models.CharField(choices=[('NO_HELMET', 'No Helmet Detected'), ('NO_MASK', 'No Mask Detected'), ('NO_SAFETY_VEST', 'No Safety Vest Detected')], max_length=50),
        ),
    ]
