# Generated by Django 5.2.5 on 2025-08-27 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0006_alert_clip_path_alert_detected_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='detected_text',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='image_caption',
        ),
        migrations.AlterField(
            model_name='alert',
            name='camera_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='alert',
            name='clip_path',
            field=models.FilePathField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='people_detected',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='alert',
            name='snapshot',
            field=models.ImageField(upload_to='snapshots/'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='violation_type',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image_caption', models.TextField(blank=True)),
                ('detected_text', models.TextField(blank=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='detector.alert')),
            ],
        ),
    ]
