# Generated by Django 5.2.5 on 2025-08-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0007_remove_alert_detected_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcription',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='alert',
            name='camera_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='clip_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='people_detected',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='snapshots/'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='violation_type',
            field=models.CharField(choices=[('NO_HELMET', 'No Helmet Detected'), ('NO_MASK', 'No Mask Detected'), ('NO_SAFETY_VEST', 'No Safety Vest Detected')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='detected_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='image_caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
