# Generated by Django 5.2.5 on 2025-08-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0008_rename_timestamp_transcription_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcription',
            name='alert',
        ),
        migrations.AddField(
            model_name='alert',
            name='detected_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='image_caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcription',
            name='camera_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
