# Generated by Django 5.2.5 on 2025-08-27 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0009_remove_transcription_alert_alert_detected_text_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transcription',
        ),
    ]
